plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.145'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    client {
        client()
    }
    server {
        server()
        programArgument '--nogui'
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${project.neo_version}"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    manifest {
        attributes([
            'Specification-Title'   : project.mod_id,
            'Specification-Vendor'  : 'Dooji',
            'Specification-Version' : '1',
            'Implementation-Title'  : project.name,
            'Implementation-Version': project.jar.archiveVersion,
            'Implementation-Vendor' : 'Dooji',
        ])
    }
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}
